(* semantically-validated AST. generated by semant.ml, sent to codegen *)

Open Ast

type sexpr = typ * sxp 
and sx =
    SLiteral of int
  | SBoolLit of bool
  | SStringLit of string
  | SId of string
  | SBinop of sexpr * op * sexpr
  | SUnop of uop * sexpr
  | SAssign of string * sexpr
  | SRetrieve of string * sexpr
  | SArray_Assign of string * sexpr * sexpr
  | SCall of string * sexpr option list

type sstmt = 
    SBlock of sstmt list
  | SExpr of sexpr
  | SReturn of sexpr option
  | SIf of sexpr * sstmt * sstmt
  | SWhile of sexpr * sstmt
  | SFor of typ * string * string * sstmt
  | SMap of string * string
  | SFilter of string * string
  | SOpen of string * string
  | SBreak

type sfunc_decl = {
    styp : typ;
    sfname : string;
    sformals : bind list;
    slocals : bind list;
    sbody : stmt list;
}




